services:
  db:
    image: postgres:13
    container_name: kittygram-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    build: ./backend
    container_name: kittygram-backend
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: kittygram-frontend
    restart: always

  gateway:
    build: ./nginx
    container_name: kittygram-gateway
    ports:
      - "8081:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media: